export const REQUEST_GANKS = 'REQUEST_GANKS'
export const RECEIVE_GANKS = 'RECEIVE_GANKS'
export const ADD_TO_READING_LIST = 'ADD_TO_READING_LIST'
export const DELETE_FROM_READING_LIST = 'DELETE_FROM_READING_LIST'